apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifecmns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifecmns
  template:
    metadata:
      labels:
        app: lifecmns
    spec:
      containers:
        - name: lifecmns
          image: lifecm:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2370

---
apiVersion: v1
kind: Service
metadata:
  name: lifecmns-service
spec:
  type: LoadBalancer
  selector:
    app: lifecmns
  ports:
    - port: 2370
      targetPort: 2370
      protocol: TCP
