// app/config/tools.ts

export interface Tool {
  id: string;
  name: string;
  category: 'pdf' | 'image' | 'media' | 'data' | 'security';
  icon: string;
  description: string;
  premium?: boolean;
}

export const categories = {
  pdf: { name: 'PDF', icon: '📄', color: 'bg-red-100 text-red-600' },
  image: { name: 'Image', icon: '🖼️', color: 'bg-blue-100 text-blue-600' },
  media: { name: 'Audio/Vidéo', icon: '🎬', color: 'bg-purple-100 text-purple-600' },
  data: { name: 'Données/Office', icon: '🧩', color: 'bg-green-100 text-green-600' },
  security: { name: 'OCR/Sécurité', icon: '🔎', color: 'bg-orange-100 text-orange-600' },
};

export const tools: Tool[] = [
  // ==================== 📄 PDF ====================
  {
    id: 'pdf-to-word',
    name: 'PDF → Word',
    category: 'pdf',
    icon: '📝',
    description: 'Convertir PDF en document DOCX éditable',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF → Excel',
    category: 'pdf',
    icon: '📊',
    description: 'Extraire tableaux vers fichier XLSX',
  },
  {
    id: 'pdf-to-ppt',
    name: 'PDF → PowerPoint',
    category: 'pdf',
    icon: '📽️',
    description: 'Convertir PDF en présentation PPTX',
  },
  {
    id: 'images-to-pdf',
    name: 'Images → PDF',
    category: 'pdf',
    icon: '🖼️',
    description: 'Combiner plusieurs images en un PDF',
  },
  {
    id: 'extract-images',
    name: 'Extraire images',
    category: 'pdf',
    icon: '🎨',
    description: 'Extraire toutes les images d\'un PDF',
  },
  {
    id: 'reorder-pages',
    name: 'Réorganiser pages',
    category: 'pdf',
    icon: '🔄',
    description: 'Réordonner et faire pivoter les pages',
  },
  {
    id: 'crop-pages',
    name: 'Recadrer pages',
    category: 'pdf',
    icon: '✂️',
    description: 'Ajuster marges et zones de coupe',
  },
  {
    id: 'protect-pdf',
    name: 'Protéger PDF',
    category: 'pdf',
    icon: '🔒',
    description: 'Ajouter un mot de passe de protection',
  },
  {
    id: 'unlock-pdf',
    name: 'Déverrouiller PDF',
    category: 'pdf',
    icon: '🔓',
    description: 'Retirer le mot de passe (si connu)',
  },
  {
    id: 'watermark-pdf',
    name: 'Filigrane PDF',
    category: 'pdf',
    icon: '💧',
    description: 'Ajouter filigrane ou numérotation',
  },
  {
    id: 'fill-forms',
    name: 'Formulaires PDF',
    category: 'pdf',
    icon: '📋',
    description: 'Remplir et aplatir des formulaires',
  },
  {
    id: 'redact-pdf',
    name: 'Occulter données',
    category: 'pdf',
    icon: '⬛',
    description: 'Masquer informations sensibles',
  },
  {
    id: 'pdf-a',
    name: 'PDF/A Archivage',
    category: 'pdf',
    icon: '🗄️',
    description: 'Convertir en format d\'archivage',
  },
  {
    id: 'compare-pdf',
    name: 'Comparer PDF',
    category: 'pdf',
    icon: '🔍',
    description: 'Différences visuelles entre deux PDF',
  },

  // ==================== 🖼️ IMAGE ====================
  {
    id: 'resize-batch',
    name: 'Redimensionner lot',
    category: 'image',
    icon: '📐',
    description: 'Redimensionner plusieurs images',
  },
  {
    id: 'heic-converter',
    name: 'HEIC Converter',
    category: 'image',
    icon: '🔄',
    description: 'HEIC vers JPG/PNG/WebP/AVIF',
  },
  {
    id: 'optimize-web',
    name: 'Optimiser Web',
    category: 'image',
    icon: '⚡',
    description: 'Réduire poids pour le web',
  },
  {
    id: 'remove-exif',
    name: 'Supprimer EXIF',
    category: 'image',
    icon: '🔏',
    description: 'Retirer métadonnées des photos',
  },
  {
    id: 'color-palette',
    name: 'Palette couleurs',
    category: 'image',
    icon: '🎨',
    description: 'Extraire les couleurs dominantes',
  },
  {
    id: 'favicon-generator',
    name: 'Générer favicon',
    category: 'image',
    icon: '🌐',
    description: 'Créer ICO et multi-tailles',
  },
  {
    id: 'image-collage',
    name: 'Collage photos',
    category: 'image',
    icon: '🖼️',
    description: 'Créer montage/grille d\'images',
  },
  {
    id: 'upscale-ai',
    name: 'Upscale IA x4',
    category: 'image',
    icon: '🔬',
    description: 'Super-résolution par IA',
    premium: false,
  },
  {
    id: 'denoise-ai',
    name: 'Débruiter IA',
    category: 'image',
    icon: '✨',
    description: 'Réduction bruit/flou IA',
    premium: false,
  },
  {
    id: 'inpainting',
    name: 'Inpainting IA',
    category: 'image',
    icon: '🪄',
    description: 'Supprimer objets intelligemment',
    premium: false,
  },
  {
    id: 'blur-background',
    name: 'Flouter arrière-plan',
    category: 'image',
    icon: '🌫️',
    description: 'Effet bokeh automatique',
  },
  {
    id: 'batch-watermark',
    name: 'Filigrane lot',
    category: 'image',
    icon: '©️',
    description: 'Ajouter logo en masse',
  },

  // ==================== 🎬 AUDIO/VIDÉO ====================
  {
    id: 'video-converter',
    name: 'Convertir vidéo',
    category: 'media',
    icon: '🎞️',
    description: 'WebM/MP4 H.264/H.265',
  },
  {
    id: 'compress-video',
    name: 'Compresser vidéo',
    category: 'media',
    icon: '🗜️',
    description: 'Réduire à taille cible',
  },
  {
    id: 'trim-video',
    name: 'Couper vidéo',
    category: 'media',
    icon: '✂️',
    description: 'Rogner sans ré-encodage',
  },
  {
    id: 'extract-audio',
    name: 'Extraire audio',
    category: 'media',
    icon: '🎵',
    description: 'Audio depuis vidéo',
  },
  {
    id: 'audio-converter',
    name: 'Convertir audio',
    category: 'media',
    icon: '🎧',
    description: 'MP3/WAV/FLAC/AAC',
  },
  {
    id: 'normalize-audio',
    name: 'Normaliser volume',
    category: 'media',
    icon: '🔊',
    description: 'Standard LUFS',
  },
  {
    id: 'noise-reduction',
    name: 'Réduire bruit',
    category: 'media',
    icon: '🤫',
    description: 'Suppression bruit IA',
    premium: false,
  },
  {
    id: 'auto-subtitles',
    name: 'Sous-titres auto',
    category: 'media',
    icon: '💬',
    description: 'Génération STT',
    premium: false,
  },
  {
    id: 'burn-subtitles',
    name: 'Graver sous-titres',
    category: 'media',
    icon: '🔥',
    description: 'Incruster dans vidéo',
  },
  {
    id: 'change-speed',
    name: 'Vitesse vidéo',
    category: 'media',
    icon: '⏩',
    description: 'Slow motion / accéléré',
  },
  {
    id: 'video-to-gif',
    name: 'Vidéo → GIF',
    category: 'media',
    icon: '🎭',
    description: 'Créer GIF optimisé',
  },

  // ==================== 🧩 DONNÉES ====================
  {
    id: 'csv-to-xlsx',
    name: 'CSV → Excel',
    category: 'data',
    icon: '📊',
    description: 'Convertir avec encodage',
  },
  {
    id: 'clean-csv',
    name: 'Nettoyer CSV',
    category: 'data',
    icon: '🧹',
    description: 'UTF-8, doublons, quotes',
  },
  {
    id: 'json-converter',
    name: 'JSON Converter',
    category: 'data',
    icon: '🔄',
    description: 'JSON ↔ YAML/XML',
  },
  {
    id: 'minify-code',
    name: 'Minifier code',
    category: 'data',
    icon: '📦',
    description: 'HTML/CSS/JS compact',
  },
  {
    id: 'text-diff',
    name: 'Comparer textes',
    category: 'data',
    icon: '🔀',
    description: 'Différences entre fichiers',
  },
  {
    id: 'markdown-converter',
    name: 'Markdown Converter',
    category: 'data',
    icon: '📝',
    description: 'MD ↔ HTML/PDF',
  },
  {
    id: 'qr-code',
    name: 'QR Code',
    category: 'data',
    icon: '📱',
    description: 'Générer et décoder',
  },
  {
    id: 'hash-generator',
    name: 'Hash / Empreinte',
    category: 'data',
    icon: '🔐',
    description: 'MD5/SHA-256',
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    category: 'data',
    icon: '🆔',
    description: 'UUID v4 / ULID',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML → PDF',
    category: 'data',
    icon: '🌐',
    description: 'Rendu navigateur',
  },

  // ==================== 🔎 SÉCURITÉ ====================
  {
    id: 'ocr-text',
    name: 'OCR Texte',
    category: 'security',
    icon: '👁️',
    description: 'Image/PDF → Texte',
    premium: false,
  },
  {
    id: 'mask-pii',
    name: 'Masquer PII',
    category: 'security',
    icon: '🎭',
    description: 'Flouter infos personnelles',
  },
  {
    id: 'metadata-tool',
    name: 'Métadonnées',
    category: 'security',
    icon: '📋',
    description: 'Extraire/retirer métadonnées',
  },
  {
    id: 'archive-tool',
    name: 'Archives ZIP/7z',
    category: 'security',
    icon: '📦',
    description: 'Créer/extraire archives',
  },
  {
    id: 'split-merge',
    name: 'Découper fichiers',
    category: 'security',
    icon: '✂️',
    description: 'Split/merge gros fichiers',
  },
];
